### PR TITLE
Fix small bugs and bothers

### PR DESCRIPTION
**Pull request by pjvandehaar**

### CODE REVIEW

**Comment by pjvandehaar** [comment]
This PR is more opinionated than its predecessors.  If you don't like the replacement of `GENES_TO_CACHE` with `FileSystemCache`, I can remove it.

**Comment by pontikos** [comment]
I approve of these changes @pjvandehaar , especially 65d884e, was about to fix this myself.
I'm trying to figure out the git command to integrate your changes into my forked repo.

**Comment by pjvandehaar** [comment]
I think it's:

```
git remote add pjvandehaar git@github.com:pjvandehaar/exac_browser.git
git fetch pjvandehaar
git checkout master
git rebase pjvandehaar/master
```

**Comment by pontikos** [comment]
Thanks @pjvandehaar but I got an error on:
```
> git fetch pjvandehaar
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

Anyway I see that @konradjk has merged the commit so your changes are now synched to my fork :)

Thanks guys :+1:

**Pull request merged**
